# Generated by Django 3.1.5 on 2021-03-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20210308_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(to='pokedex.PokemonType'),
        ),
    ]
