# Generated by Django 3.1.5 on 2021-03-23 02:43

from django.db import migrations, models
import django.db.models.deletion
import support.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_type', models.CharField(max_length=32)),
                ('support_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('message', models.TextField(max_length=1024)),
                ('image', models.ImageField(default=None, upload_to=support.models.user_directory_path)),
                ('iphone', models.CharField(max_length=48)),
                ('ios', models.CharField(max_length=16)),
                ('reponse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support', to='support.supporttype')),
            ],
        ),
    ]
