# Generated by Django 3.1.5 on 2021-03-23 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='reponse',
            new_name='response',
        ),
    ]
