# Generated by Django 3.1.5 on 2021-03-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20210322_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporttype',
            name='support_id',
        ),
        migrations.AddField(
            model_name='support',
            name='prior_support_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
