# Generated by Django 3.1.5 on 2021-03-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20210324_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='responsed_too',
            field=models.BooleanField(default=False),
        ),
    ]
