# Generated by Django 3.1.5 on 2021-03-28 00:04

from django.db import migrations, models
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_support_responsed_too'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='image',
            field=models.ImageField(blank=True, upload_to=support.models.user_directory_path),
        ),
    ]
