noun1 = input("Enter a noun: ")
noun2 = input("Enter another noun: ")
noun3 = input("Enter another noun: ")
verb = input("Enter a verb: ")
occupation = input("Enter an occupation: ")
place1  = input("Enter a place: ")
place2  = input("Enter a nother place: ")
verd_ending_in_ed = input("Enter a verb end in \"ed\": ")
noun4 = input("Enter another noun: ")
verd_ending_in_ing = input("Enter a ver b end in \"ing\": ")
plural_noun = input("Enter a pural noun: ")
noun5 = input("Enter another noun: ")
place3  = input("Enter a place: ")
emotion  = input("Enter an emition: ")
 
print(f"It was during the battle of {noun1} when I was running through a {noun2} when a {noun3} went off right next to my platoon. Our {occupation} yelled for us to {verb} to the nearest {place1} we could find. When we got to the {place2} we {verd_ending_in_ed} to start a fire. As we were starting the fire the enemy saw the {noun4} from the fire and started {verd_ending_in_ing} {plural_noun} at us. we all quickly ducked behind the {noun5} at the {place3} and returned fire. we quickly eliminated the enemy and  were {emotion} that we had won the battle.")
