# Generated by Django 3.1.5 on 2021-03-05 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='todo.priority'),
        ),
    ]
