# Generated by Django 3.1.5 on 2021-03-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsy',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
